### PR TITLE
Add documentation for MR2 features for mobile

### PR DESCRIPTION
**Pull request by jhugman**
This PR adds documentation for:

 * structural types and enums for feature-variables. These were added in [SDK-367][1], https://github.com/mozilla/application-services/pull/4455
 * enabling multi-features. This was added in [SDK-365][2]

[1]: https://mozilla-hub.atlassian.net/browse/SDK-367
[2]: https://mozilla-hub.atlassian.net/browse/SDK-365

### CODE REVIEW

**Review by tarikeshaq — APPROVED** [review]
💯 

One side thought about how we do mobile docs... The same documentation can be found under both the `iOS` and `Android` sections on the website, and includes information relevant to both, but as an `Android` engineer, it includes information about `iOS` I may not be interested in.. Nothing urgent to fix here, but I think we should have a clearer story of how we want the docs structured in general in the future.. 
- A) Do we want to have a different doc for `Android` and for `iOS`, each referenced in their respective sidebar items?
- B) Do we want to have the same doc that is referenced by both sidebar items (like this doc is)?
- C) Do we want to replace the `Firefox for Android` and `Firefox for iOS` sections with a more compact `Firefox for Mobile` and have **that** do option `A`

I think the answer will depend on how different the documentation will be once it evolves a bit more, if `iOS` and `Android` start diverging a ton, it'll be a pain to have them in the same doc

**Comment by travis79** [comment]
> 💯
> 
> One side thought about how we do mobile docs... The same documentation can be found under both the `iOS` and `Android` sections on the website, and includes information relevant to both, but as an `Android` engineer, it includes information about `iOS` I may not be interested in.. Nothing urgent to fix here, but I think we should have a clearer story of how we want the docs structured in general in the future..
> 
>     * A) Do we want to have a different doc for `Android` and for `iOS`, each referenced in their respective sidebar items?
> 
>     * B) Do we want to have the same doc that is referenced by both sidebar items (like this doc is)?
> 
>     * C) Do we want to replace the `Firefox for Android` and `Firefox for iOS` sections with a more compact `Firefox for Mobile` and have **that** do option `A`
> 
> 
> I think the answer will depend on how different the documentation will be once it evolves a bit more, if `iOS` and `Android` start diverging a ton, it'll be a pain to have them in the same doc

One clever way we solved this for Glean was to combine the information into blocks where you can select the relevant platform/language from a tab.  For instance: https://mozilla.github.io/glean/book/reference/metrics/boolean.html

**Comment by jhugman** [comment]
As the feature-variables-and-me doc gets bigger, I can definitely see a point to separating it out into platforms. 

I can also see: 

* there's engineering documentation and product/design docs. This document tries to straddle them both, with the API docs taking the burden of what calls mean.
* code generation is going to make all these things much much simpler as documentation becomes about the manifest.

**Comment by jhugman** [comment]
Merged with a followup bug.

**Pull request merged**
