### PR TITLE
fix #7306 - add how to iterate desktop exp locally

### PR DESCRIPTION
**Pull request by dmose**
## Issue that this pull request resolves (optional)

This will link to and close an issue in GitHub. Replace `experimenter` with the repository where the issue lives and replace `0000` with the issue number. Remove this section if not applicable.

Closes: mozilla/experimenter#7306

### CODE REVIEW

**Comment by dmose** [comment]
CC @brennie

**Comment by jaredlockhart** [comment]
@dmose How does this relate to the documented desktop testing process described in:

https://experimenter.info/workflow/preview

Is this for cases where that doesn't work?

**Comment by dmose** [comment]
> @dmose How does this relate to the documented desktop testing process described in:
>
> Is this for cases where that doesn't work?

In general, that's not a very fast workflow, because the experiment data is behind a CDN that can take a while to update.  So if you need to iterate quickly to figure out exactly what's going to work, it's extremely painful. I could totally imagine that there are reasonable ways to fix that, in which case this might not be needed.

**Comment by jaredlockhart** [comment]
Oh right I see, we should be able to bypass the CDN step by pointing the browser directly at the remote settings server URL:

https://settings.prod.mozaws.net/

instead of the CDN URL:

https://firefox.settings.services.mozilla.com/

in the pref:

`services.settings.server`


Do you wanna try that locally and see if it gets around the slow CDN step and then if that works we can amend the instructions to say that?

**Review by jaredlockhart — APPROVED** [review]
Okay new plan!

I just got off the phone with leplatrem and he pointed a few interesting things out

1) remote settings is soon disabling the ability to modify its behaviour via prefs altogether for security reasons (so my proposal won't work at all)

2) using remote settings as part of the preview workflow puts some strain on remote settings/push

3) the proposal here, bypassing remote settings altogether, is actually the ideal workflow

So thank you for writing this up, let's land this, and then maybe at some point we can wrap this in an addon to streamline the workflow 🙏 

Thanks @dmose ! 🎉 🎉 🎉

**Comment by dmose** [comment]
Another possibility is just adding this into about:studies when nimbus.debug is set.

**Pull request merged**
